<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.Actor.Tests" Version="30.0.0-juliet.0.ci.23" />
    <PackageReference Include="CK.DB.Auth.Tests" Version="30.0.0-juliet.0.ci.23" />
    <PackageReference Include="CK.Cris.Engine" Version="2.0.0-juliet.0.ci.15" />
    <PackageReference Include="CK.Poco.Exc.Json.Engine" Version="35.0.0-juliet.0.ci.8" />
    <PackageReference Include="CK.TypeScript.Engine" Version="2.0.0-juliet.0.ci.10" />
    <PackageReference Include="CK.DB.Tests.NUnit" Version="35.0.0-juliet.0.ci.14" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.DB.UserInvitation\CK.DB.UserInvitation.csproj" />
  </ItemGroup>
</Project>