<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" Exclude="bin\**;obj\**;CodeCakeBuilder\**;packages\**;@(EmbeddedResource)" />
    <None Remove="Res\**\*.sql;Res\**\*.tql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.Actor" Version="29.0.1--ci.1" />
    <PackageReference Include="CK.DB.Auth" Version="29.0.1--ci.1" />
    <PackageReference Include="CK.DB.Culture" Version="29.0.1--ci.1" />
    <PackageReference Include="CK.SqlServer.Dapper" Version="16.0.1--ci.1" />
    <PackageReference Include="CK.SqlServer.Transaction" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.UserInvitation\CK.IO.UserInvitation.csproj" />
  </ItemGroup>
</Project>